databases:
  - name: landingburn
    databaseName: landingburn
    user: landingburn

services:
  - type: web
    name: landingburn
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/rails db:migrate"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: landingburn
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: worker
    name: landingburn-worker
    runtime: ruby
    buildCommand: "./bin/render-worker-build.sh"
    startCommand: "./bin/rails solid_queue:start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: landingburn
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
